### PR TITLE
List commits

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Adds field containing all the git commit information one could possibly need for each page.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Targets #5

**Comment by matthiasbeyer** [comment]
I am thinking about a feature where you can show the diff as well.

If you wait with the merge, I will try to add such a feature (switched off by default) to my PR. If you want to merge asap, go ahead, I will open another PR for this.

**Comment by ivantsepp** [comment]
I really like this feature. But I'm starting to think there might be too much git data. Could we make this optional and toggleable through a config?

**Comment by matthiasbeyer** [comment]
This PR is two years old, I'm no longer interested in jekyll, I'm sorry. Feel free to reuse these commits as you please.

**Comment by ivantsepp** [comment]
😭 sorry for not getting to this. I'll take a look at your implementation and see what I can do 😄

**Pull request closed without merging**
